name: Manage AzKV Secrets

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Secret Name'
        required: true
      secretValue:
        description: 'Secret Value'
        required: true
      keyvaultName:
        description: 'Keyvault Name'
        required: true

jobs:
  update-kv-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - id: check-secret
      name: Check Secret
      run: |
        secret=$(az keyvault secret list --vault-name ${{ github.event.inputs.keyvaultName }} --query "[?name=='${{ github.event.inputs.secretName }}']" -o tsv)
        if [ -z "$secret" ]; then
          echo "Secret not found"
          exit 1
        fi

    - name: Update Secret
      if: ${{ success() }}
      run: |
        az keyvault secret set --vault-name ${{ github.event.inputs.keyvaultName }} --name ${{ github.event.inputs.secretName }} --value ${{ github.event.inputs.secretValue }}
